### ISSUE TITLE
[test] As dev, I'd like my test to run on a toy dataset in a reasonable time frame 

### ISSUE THREAD

**Issue by dagousket** [balglave/FishMap#10]
[test] As dev, I'd like my test to run on a toy dataset in a reasonable time frame 

## Client - Validation 

What we want to achieve after the problems are addressed:

+ [x] Running the package check completes in a reasonable time frame

total runtime of `main.R` before edits from PR #13 was >15min. Total runtime after edits from PR #13 is now <3min and satisfactory for future use in unit tests.

```
Timing information before speed optimisation (samp_process = 0):
Step 3 -fit model-: 8.53 mins
-compute sd-: 4.59 mins

Timing information after speed optimisation:
Step 1 -loading data-: 21.365 sec elapsed
Step 2 -compile model-: 71.491 sec elapsed
Step 3 -fit model-: 75.92 sec elapsed
Step 4 -plot graphs-: 1.316 sec elapsed

```

## Tech - For developers only

+ [x] Use a reduced dataset (See https://github.com/balglave/FishMap/pull/13)
+ [x] Use env. vars to specify the addition of longer tests in check. Use dev realised in https://github.com/balglave/FishMap/issues/9
    + Ce dossier output_dir, nuos l'utilisons en interne comme ref pour nos tests unitaires.
    + Une variable d'environnement permettra d'écrire dedans ou non. (modifié) 

## Problems adressed

- Calculation are long and increase development time for each checks
- A proposition to use `samp_process = 0` reduces time but is still too long for daily checks (~10min)

### Questions

We can work on two ways: reduce development time, or reduce outputs size. 
Reducing time, would allow to run the model more frequently. Reducing size, would allow to include some outputs inside the package for tests after model fits.

We need to address this problem if we want to work in a robust development context. Otherwise, only code used before the model fit will be properly documented and tested.

- [x] Would it be possible for you to reduce the spatial extent for instance ?
     - Will this affect the capacity of the model to converge ? Will this reduce time ?
     
Concerning size and storage, we would need **full day of work** for exploration (See details below)  

- [x] Do we use this exploration day now, or do we wait for you to propose other solutions with reduced time or with reduced model outputs storage size ?

### Propositions for size and storage exploration

- We would need to explore some possibilities on how to deal with these long calculations. 
    - We need to explore the possibility to store the intermediate outputs, but there are about 1Go, so we cannot add them in the repository
    - We can define a environment variable to test the values locally only, on manual demand
    - We need to prevent CI to test the model calculation for each commit. Maybe this can only be run when merged to 'main' branch, but this requires to rework the CI configuration.

**Comment by dagousket** [comment]
Using `samp_process <- 0` in the model config, the two longer steps take 8.53 mins (`nlminb()`) and 4.59 mins (`sdreport()`) respectively.

**Comment by balglave** [comment]
I modified the main codes to make it faster. It is in 'client' branch. [link](https://github.com/balglave/FishMap/blob/0f327801e81c1c8f99dcff041d7c16716c7ea49a/dev/r_scripts_orig/main.R)

The model now runs in 2min30 (I only run nlminb, sdreport can be left appart).

To do so, I:
- reduced the time span to only 1 month (should be enough for validation)
- reduce the mesh size (k = 0.25 now) --> this is equivalent as reducing the spatial extent. I only reduce the number of knots at which the spatial random effect is computed.
- skipped the sdreport step. This is a step for computing standard deviations and they are not required in the codes.

Let me know if this fine for you.

Otherwise another possibility is to limit the number of iteration in estimation without caring about convergence. This is the maxit argument in nlminb. You can reduce it to 50 or 10 if this is better for you.

**Comment by balglave** [comment]
Je valide
